name: Typecheck

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Use correct Yarn version
        run: corepack prepare yarn@4.5.2 --activate

      - name: Install Dependencies
        run: yarn install

      - name: Run Typecheck
        run: yarn github:typecheck